/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react'
import { Html, useGLTF, useTexture } from '@react-three/drei'

import "./Popup.css";

import Model from './phone.gltf';
import Tex from './Home Screen.png';


function MockupMesh ({ node }) {

  const matRef = useRef()
  const colorInpRef = useRef()
  const metalnessInpRef = useRef()
  const roughnessInpRef = useRef()

  // const tex = useTexture(Tex)
  const [hovering, setHovering] = useState(false)
  const [showMenu, setShowMenu] = useState(false)


  const hexToRgb = (hex) => {
    // https://stackoverflow.com/questions/5623838/rgb-to-hex-and-hex-to-rgb
    var shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
    hex = hex.replace(shorthandRegex, function(m, r, g, b) {
      return r + r + g + g + b + b;
    });
  
    var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return `rgb(${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)})`
  }
  function rgbToHex(r, g, b) {
    return "#" + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1);
  }


  const setMeshColor = () => { matRef.current.color.set( hexToRgb(colorInpRef.current.value) ) }
  const setMeshMetalness = () => { matRef.current.metalness = metalnessInpRef.current.checked ? 1 : 0 }
  const setMeshRoughness = () => { matRef.current.roughness = roughnessInpRef.current.value }


  useEffect(() => {
    if (hovering) { document.body.classList.add("pointing") }
    else { document.body.classList.remove("pointing") }
  }, [hovering])


  useEffect(() => {
    if (showMenu) {
      let { r, g, b } = matRef.current.color
      colorInpRef.current.value = rgbToHex(Math.round(r*255), Math.round(g*255), Math.round(b*255))
      metalnessInpRef.current.checked = Boolean(matRef.current.metalness)
      roughnessInpRef.current.value = matRef.current.roughness
    }
  }, [showMenu])

  return (
    <group>
      <mesh
        onPointerOver={()=>setHovering(true)}
        onPointerOut={()=>setHovering(false)}
        onClick={()=>setShowMenu(!showMenu)}
        castShadow
        receiveShadow
        geometry={node.geometry}
      >
        <meshStandardMaterial
          ref={matRef}
          roughness={0.2}
          metalness={0}
          color="orange"
          emissive={hovering ? "orange" : "white"}
          emissiveIntensity={hovering ? 5 : 0}
        />
      </mesh>

      {showMenu && <Html className="materialPopup" position={node.geometry.boundingBox.max}>
        <input type="color" ref={colorInpRef} onChange={setMeshColor} />
        <input type="checkbox" ref={metalnessInpRef} onChange={setMeshMetalness} />
        <input type="range" ref={roughnessInpRef} min="0" max="1" step={0.01} onChange={setMeshRoughness} />
      </Html>}
    </group>
  )
}


export default function Shoebox(props) {

  const group = useRef()
  const { nodes, materials } = useGLTF(Model)

  return (
    <group ref={group} {...props} dispose={null}>
      <MockupMesh node={nodes.Plane001}/>
      <MockupMesh node={nodes.Plane011}/>
      <MockupMesh node={nodes.Plane011_1}/>
      <MockupMesh node={nodes.Plane011_2}/>
      <MockupMesh node={nodes.Plane011_3}/>
      <MockupMesh node={nodes.Plane011_4}/>
      <MockupMesh node={nodes.Plane002}/>
      <MockupMesh node={nodes.Plane014}/>
      <MockupMesh node={nodes.Plane014_1}/>
      <MockupMesh node={nodes.Circle001_1}/>
      <MockupMesh node={nodes.Circle001_2}/>
      <MockupMesh node={nodes.Circle001}/>
      <MockupMesh node={nodes.Circle003}/>
      <MockupMesh node={nodes.Circle002}/>
      <MockupMesh node={nodes.Plane004}/>
      <MockupMesh node={nodes.Circle008}/>
      <MockupMesh node={nodes.Circle008_1}/>
      <MockupMesh node={nodes.Plane005}/>
      <MockupMesh node={nodes.Plane006}/>
      <MockupMesh node={nodes.Plane007}/>
    </group>
  )
}

useGLTF.preload(Model)
