/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react'
import { Html, useGLTF, useTexture } from '@react-three/drei'
import { FaCheck } from 'react-icons/fa';

import "./Popup.css";

import Model from './phone.gltf';
import Tex from './Home Screen.png';


function MockupMesh ({ node, selected, setSelected }) {

  const matRef = useRef()
  const colorInpRef = useRef()
  const metalnessInpRef = useRef()
  const roughnessInpRef = useRef()

  // const tex = useTexture(Tex)
  const [hovering, setHovering] = useState(false)


  const hexToRgb = (hex) => {
    // https://stackoverflow.com/questions/5623838/rgb-to-hex-and-hex-to-rgb
    var shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
    hex = hex.replace(shorthandRegex, function(m, r, g, b) {
      return r + r + g + g + b + b;
    });
  
    var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return `rgb(${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)})`
  }
  function rgbToHex(r, g, b) {
    return "#" + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1);
  }


  const setMeshColor = () => { matRef.current.color.set( hexToRgb(colorInpRef.current.value) ) }
  const setMeshMetalness = () => { matRef.current.metalness = metalnessInpRef.current.checked ? 1 : 0 }
  const setMeshRoughness = () => { matRef.current.roughness = roughnessInpRef.current.value }


  useEffect(() => {
    if (hovering) { document.body.classList.add("pointing") }
    else { document.body.classList.remove("pointing") }
  }, [hovering])


  useEffect(() => {
    if (selected === node.geometry.uuid) {
      let { r, g, b } = matRef.current.color
      colorInpRef.current.value = rgbToHex(Math.round(r*255), Math.round(g*255), Math.round(b*255))
      metalnessInpRef.current.checked = Boolean(matRef.current.metalness)
      roughnessInpRef.current.value = matRef.current.roughness
    }
  }, [selected])

  return (
    <>
    <group>
      <mesh
        onPointerOver={()=>setHovering(true)}
        onPointerOut={()=>setHovering(false)}
        onClick={()=>setSelected(node.geometry.uuid)}
        castShadow
        receiveShadow
        geometry={node.geometry}
      >
        <meshStandardMaterial
          ref={matRef}
          roughness={0.2}
          metalness={0}
          color="orange"
          emissive={hovering ? "orange" : "white"}
          emissiveIntensity={hovering ? 5 : 0}
        />
      </mesh>

      {selected === node.geometry.uuid && <Html position={node.geometry.boundingBox.max}>
        <div className="materialPopup">
          <p>Color</p>
          <input type="color" ref={colorInpRef} onChange={setMeshColor} />
          <p>Metal</p>
          <input type="checkbox" ref={metalnessInpRef} onChange={setMeshMetalness} />
          <p>Roughness</p>
          <input type="range" ref={roughnessInpRef} min="0" max="1" step={0.01} onChange={setMeshRoughness} />
          <button className="popupConfirm" onClick={()=>setSelected(null)}><FaCheck size={16} color="limegreen"/></button>
        </div>
      </Html>}

    </group>
    </>
  )
}


export default function Shoebox(props) {

  const group = useRef()
  const { nodes, materials } = useGLTF(Model)

  const [selectedUid, setSelectedUid] = useState(null)

  return (
    <group ref={group} {...props} dispose={null} >
      <MockupMesh node={nodes.Plane001} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane011} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane011_1} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane011_2} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane011_3} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane011_4} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane002} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane014} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane014_1} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Circle001_1} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Circle001_2} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Circle001} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Circle003} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Circle002} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane004} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Circle008} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Circle008_1} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane005} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane006} selected={selectedUid} setSelected={setSelectedUid} />
      <MockupMesh node={nodes.Plane007} selected={selectedUid} setSelected={setSelectedUid} />
    </group>
  )
}

useGLTF.preload(Model)
