/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

import Model from './phone.gltf';
import Tex from './Home Screen.png';

export default function Shoebox(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(Model)
  const tex = useTexture(Tex)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011_1.geometry}
        material={nodes.Plane011_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011_2.geometry}
        material={materials.Pantalla}
      >
        <meshStandardMaterial roughness={0.025} metalness={0} map={tex} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011_3.geometry}
        material={nodes.Plane011_3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011_4.geometry}
        material={materials['Bandas magneticas']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014_1.geometry}
        material={nodes.Plane014_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_1.geometry}
        material={nodes.Circle001_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001_2.geometry}
        material={nodes.Circle001_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials['Luz Led']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008.geometry}
        material={materials['Metal Ceramico']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008_1.geometry}
        material={materials.Cobre}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
      />
    </group>
  )
}

useGLTF.preload(Model)
